site_name: The Idea Vault
site_url: https://sitename.example

repo_name: RafanHRayan/The-Idea-Vault
repo_url: https://github.com/RafanHRayan/The-Idea-Vault

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: Inclusive Sans #IBM Plex Sans
    code: JetBrains Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
    primary: black
    accent: custom
  # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
    primary: white
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - toc:
      toc_depth: 5
  - abbr

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RafanHRayan

copyright: Copyright &copy; 2025 Rafan H. Rayan

nav:
  - Home:
    - index.md
    - Reference: ref.md
    - Changelog:
        - changelogs/index.md
        - Past Changelogs:
          - 2025 Changelog: changelogs/past-changelogs/2025.md
  - Mathematics:
    - mathematics/index.md
    - Fundamental:
      - Geometry:
        - mathematics/fundamental/geometry/index.md
        - Logic: mathematics/fundamental/geometry/01_logic.md